### ISSUE TITLE
[docs] The plugin should work offline

### ISSUE THREAD

**Issue by stasadev** [albertlauncher/plugins#117]
#### Description
When I use the Docs plugin, I expect not only quick access to documentation, but also the ability to search it offline.

Plugin version: docs v1.4

#### Expected behavior
Basically, I want the same behavior as in the Emoji plugin, where everything is loaded from `~/.cache/albert/emoji/`.

In the case of Docs, the docset list can be loaded from the cache  `~/.cache/albert/docs/icons/` (the startup error `Error fetching docset list` can be hidden).

#### Steps to reproduce
1. Enable Python and Docs plugins into Settings > Plugins
2. Download any docset
3. Disable the Internet and Restart Albert
4. See an error `Error fetching docset list: Host api.zealdocs.org not found`
5. Try to search in Docs with `docs <something>`
6. See nothing

#### Source
AUR

**Comment by stasadev** [comment]
Ok, I got it, no problem.

> If you really want to have offline docs use zeal

I'm already using Zeal, but searching inside Albert looks more appealing, thanks for making this plugin available!

> No offense Oleg 😅. 

I have a different name 😂.

> you are free to pimp the plugin.

I'll think about it, it doesn't seem too difficult to cache https://api.zealdocs.org/v1/docsets.

**Comment by ManuelSchneid3r** [comment]
> I have a different name 😂.

just an inline note for the zeal dev who potentially could read the CC in the community chat :D

**Comment by stasadev** [comment]
I prepared a PR, check it out when you have time @ManuelSchneid3r.

**Comment by brenns10** [comment]
Interestingly, I found you can simply replace the URL for the docset list with a `file:///` where you have downloaded the docsets. This is quite useful if you want to build your own docset, because you can create a JSON object for the docset, and then stick the fake item into the JSON file, and place your docset into the `~/.local/share/albert/docs/docsets/` directory. This has the happy coincidence of allowing offline offline access, and also allowing you to use unofficial docsets, e.g. those created from `doc2dash` or `mandocset`. If your pull request is accepted, I might try to add on to it a bit to allow my use of unofficial docsets.
