### ISSUE TITLE
[python] Ability to respond to a Python plugin without a defined trigger

### ISSUE THREAD

**Issue by DenverCoder1** [albertlauncher/plugins#83]
With 0.17, I was able to make some plugins that respond to plaintext queries rather than ones prefixed by a specific "trigger".

Is it possible with 0.18 to have plugins that do not have a prefix trigger, in other words, it will display items conditionally based on a regex match?

For example, I want to be able to trigger plugins with things like `15 min to sec` or `9pm MST in New York`.

I tried setting `defaultTrigger` to `return ""`, and it works the first time, but if I create another plugin the same way, it crashes with `Duplicate extension registration`.

**Comment by ManuelSchneid3r** [comment]
This is intended for now. The internal machinery changed. There are item providers, global query handlers and triggered handlers.
Python is problematic in the sense that it cant be paralleled due to the global interpreter lock. This is shit an defeats the internal multithreading of query handlers. As such we can't work around this and if a plugin author decides to eg use requests (sync network query) the entire global query will be blocked until it. finished

**Comment by ManuelSchneid3r** [comment]
Oops qcidentially hit the button

**Comment by ManuelSchneid3r** [comment]
Futher I am not that satisfied yet with the way global query handlers work. Plugin devs have to apply the user score. If they forget items will be ranked higher. This will have to change. So for now there are only triggered queries until indexqueryhandler and global queryhandler

**Comment by ManuelSchneid3r** [comment]
You could still write a c++ plugin though. The python interface is a scripting api, which has never been intended to expose the full feature set. (especially because there are such dealbreakers like the GIL)
